name: Backend dev ci

on:
  pull_request:
    branches: ['dev']
    paths:
      - 'packages/server/**'
      - '.github/workflows/be-dev-ci.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './packages/server'

    steps:
      - name: checkout to the branch
        uses: actions/checkout@v3

      - name: node set-up
        uses: actions/setup-node@v3
        with:
          node-version: 18.6.0

      - name: Install dependencies
        run: npm install

      - name: Inject Environment Variables
        env:
          BE_DEV_ENV: ${{ secrets.BE_DEV_ENV }}
        run: echo "$BE_DEV_ENV" > .dev.env

      - name: Test
        run: npm run test:cov
        env:
          CI: false
